# !/bin/bash
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/
    steps:
      - name: Build kernel
        run: ./build-kernel.sh
      - name: Make bootstrap
        run: ./bootstrap-base.sh
      - name: Make image
        run: ./build-image-final.sh